# -*- coding: utf-8 -*-
"""S.Pavan Kumar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZk13XTSCQYbtvHyY1Ahzv727_t0eh58
"""

print("Pavan")

Name=input("ENter Name")
print("Your NAme is :",Name)

num1=int(input("enter first number"))

num2=int(input("enter second number"))
print("num1:",num1)
print("num2:",num2)

num1=int(input("enter first number"))

num2=int(input("enter second number"))
hey=num1+num2
print(hey)

num1=int(input("enter first number"))

num2=int(input("enter second number"))
num1=num1+num2
num2=num1-num2
num1=num1-num2
print(num1,num2)

a=10
b="hello"
c=2.34
print(type(a))
print(type(b))
print(type(c))

x=(10,20,30,40,50)
y=[10,20,30,40,50]
z={"one":1,"two":2}
print(type(x))
print(type(y))
print(type(z))

a=int(input(""))
b=a**2
print(b)

a=int(input(""))
b=int(input(""))
c=int(input(""))
d=(a+b+c)/3
print(d)

num1=int(input(""))
num1=num1*60
print(num1)

num1=float(input(""))
num2=float(input(""))
num3=float(input(""))
num4=num1*num2*num3
print(num4)

num1=int(input(""))
num2=int(input(""))
num3=int(input(""))
largest=max(num1,num2,num3)
print(largest)

n=100
for i in range(1,n+1):
  if(i%2==0):
    print(i)

n=100
for i in range(0,n):
  if(i%2!=0):
    print(i)

Pan=bool(input(""))
aadhar=bool(input(""))
cibil_score=int(input(""))
if(Pan and aadhar and cibil_score>750):
  print("loan approved")
else:
  print("loan rejected")

a=10
b=20
c=a+b
d=a-b
e=a*b
f=a/b
print(c,d,e,f)

a=int(input(""))
b=int(input(""))
if(a>b or a==b and b>20):
  print("true")
else:
  print("false")

num1=int(input(""))
if(num1>0):
  print("postitive")
elif(num1<0):
  print("negative")
elif(num1==0):
  print("zero")
else:
  print("error")

num1=int(input(""))
if(num1%5==0 and num1%11==0):
  print("yes")
else:
  print("no")

theory=int(input(""))
practical=int(input(""))
total=theory+practical
if(theory>=30 and practical>=20 and total>3=50):
  print("pass",total)
else:
  print("fail:",total)

age=int(input(""))
if(age>13):
  print("child")
elif(age>=13 and age<=19):
  print("Teenage")
elif(age>19):
  print("old")
else:
  print("enter a valid age")

marks=int(input(""))
if(marks>=90 and marks<=100):
  print("A")
elif(marks>=80 and marks<=89):
  print("B")
elif(marks>=70 and marks<=79):
  print("C")
elif(marks>=60 and marks<=69):
  print("D")
elif(marks>=50 and marks<=59):
  print("E")
elif(marks>=0 and marks<=49):
  print("Fail")

User=input("")
Pass=int(input(""))
user_name="Pavan"
user_pass=1234
if(User==user_name):
  print("access approved")
  if(Pass==user_pass):
    print("access approved")
  else:
    print("access denied")

else:
  print("access denied")

num1=int(input(""))
num2=int(input(""))
operator=input("type only oper:")
if(operator=="+"):
  print(num1+num2)
elif(operator=="-"):
  print(num1-num2)
elif(operator=="*"):
  print(num1*num2)
elif(operator=="/"):
  print(a/b)

temp=int(input(""))
if(temp>=96):
  print("normal")
elif(temp>96 and temp<98):
  print("cold")
elif(temp>=99 and temp<=105):
  print("fever")
elif(temp>105 and 110):
  print("high fever")
else:
  print("error")